name: build and publish a Docker image

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if the base image changed
        id: check
        uses: twiddler/is-my-docker-parent-image-out-of-date@main
        with:
          parent-image: php:8-apache
          my-image: ghcr.io/cantorgymnasium/php:main

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        if: steps.check.outputs.out-of-date == 'true'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        if: steps.check.outputs.out-of-date == 'true'
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        if: steps.check.outputs.out-of-date == 'true'
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
